apiVersion : apps/v1
kind: Deployment
metadata:
  name: theerdha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: theerdha
  template:
    metadata:
      labels:
        app: theerdha 
    spec:
      containers:
        - name: theerdha 
          image: azure/nazure:latest
          ports:
          - containerPort: 8080
